# Generated by Django 5.1.1 on 2024-09-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Студент', 'Студент'), ('Менеджер', 'Менеджер'), ('Учитель', 'Учитель'), ('Админ', 'Админ')], max_length=100, null=True, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровень',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(null=True, upload_to='static/images/', verbose_name='Фото')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('phone', models.CharField(help_text='+375_________', max_length=255, verbose_name='№ телефона')),
                ('e_mail', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('nickname_tg', models.CharField(max_length=255, null=True, verbose_name='Никнейм Telegram')),
                ('nickname_inst', models.CharField(max_length=255, null=True, verbose_name='Никнейм Instagram')),
                ('group_number', models.CharField(max_length=255, verbose_name='№ группы')),
                ('number_of_points', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('status', models.CharField(choices=[('Учится', 'Учится'), ('В академ. отпуске', 'В академ. отпуске'), ('Возврат', 'Возврат'), ('Закончил обучение', 'Закончил обучение')], max_length=100, verbose_name='Статус')),
                ('package', models.CharField(max_length=255, verbose_name='Пакет')),
                ('internship', models.CharField(max_length=255, verbose_name='Стажировка')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.level', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
