# Generated by Django 5.1.1 on 2024-11-11 22:22

import student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', validators=[student.validators.validate_image], verbose_name='Фото'),
        ),
    ]
